version: '3.7'
services:
    odtk-runtime:
        image: ansys/odtk/odtk-runtime:7.7.1-ubi8
        build: 
            context: .
            args:
                # Uncomment the first line below if you want to use the UBI image from ironbank
                # baseImage: registry1.dso.mil/ironbank/redhat/ubi/ubi8:latest
                # Uncomment the first line below if you want to use the custom UBI image made in custom-environment
                # baseImage: custom/redhat/ubi8:latest
                baseImage: redhat/ubi8:latest
        ports:
            - 9393:9393
        env_file: ../configuration/licensing.env
